services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile   # Your Node.js app Dockerfile at the project root
    ports:
      - "3000:3000"
    depends_on:
      - llm

  llm:
    build:
      context: ./LLM
      dockerfile: Dockerfile   # This refers to /rootOfTheProject/LLM/Dockerfile
    ports:
      - "11434:11434"
